### ISSUE TITLE
Error loading QtQuick 1.1

### ISSUE THREAD

**Issue by madpipeline** [hipersayanX/cpu-temperature-meter#3]
![image](https://cloud.githubusercontent.com/assets/3527534/6313818/673aa7f4-b9c7-11e4-98bd-f90f5aa8ff78.png)

I'm running Kubuntu 14.10 with Plasma 5.2.

**Comment by hipersayanX** [comment]
I have updated the [plasmoid](https://github.com/hipersayanX/cpu-temperature-meter/releases).
